services:
  - type: web
    name: po-hub
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/main.py"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:mmFLYjNfzUhg4oNz@db.hiwzweckrfjmjucbghmp.supabase.co:5432/postgres?sslmode=require"
      - key: PORT
        value: "8080"
      - key: HOST
        value: "0.0.0.0"
